export type ServiceCategory =
  | "audio-dj"
  | "special-effects"
  | "shows"
  | "decor"

export type CatalogPackage = {
  id: string
  name: string
  nameEs: string
  category: ServiceCategory
  categoryLabel: string
  categoryLabelEs: string
  price: number
  duration: string
  durationEs: string
  includes: string[]
  includesEs: string[]
  variants?: { label: string; labelEs: string; price: number }[]
  featured?: boolean
  tier?: "starter" | "mid" | "premium" | "luxury"
  image: string
}

export const CATALOG: CatalogPackage[] = [
  // ── Audio & DJ Packages ──
  {
    id: "cabina-blanca",
    name: "Cabina Blanca",
    nameEs: "Cabina Blanca",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 4830,
    duration: "5 hrs",
    durationEs: "5 hrs",
    includes: [
      '2x 15" speakers',
      "Versatile DJ + staff",
      "Microphone",
      "White booth",
    ],
    includesEs: [
      '2 medios 15" (bocinas)',
      "DJ versátil + staff",
      "Micrófono",
      "Cabina blanca",
    ],
    tier: "starter",
    image: "/images/service-audio.jpg",
  },
  {
    id: "magic",
    name: "Magic",
    nameEs: "Magic",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 6820,
    duration: "5 hrs",
    durationEs: "5 hrs",
    includes: [
      '2x 15" speakers',
      "LED lighting",
      "Versatile DJ / Staff",
      "Illuminated pixel booth",
      "2 beam moving heads",
      "2 lighting towers",
      "Microphones",
      "Event hosting",
      "Souvenirs (balloons, ties, wands, etc.)",
    ],
    includesEs: [
      '2 medios 15" (bocinas)',
      "Iluminación LED",
      "DJ Versátil / STAFF",
      "Cabina Pixeles iluminada",
      "2 Cabezas móviles beam",
      "2 Torres para Iluminación",
      "Micrófonos",
      "Conducción del evento",
      "Souvenirs (Globos, corbatas, varitas etc...)",
    ],
    tier: "starter",
    image: "/images/service-audio.jpg",
  },
  {
    id: "party",
    name: "Party",
    nameEs: "Party",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 8140,
    duration: "5 hrs",
    durationEs: "5 hrs",
    includes: [
      '2x 15" speakers',
      '2x 18" subwoofers',
      "2 beam moving heads",
      "2 wash moving heads",
      "2 lambrin lighting towers",
      "Versatile DJ / Staff",
      "Souvenirs (balloons, ties, wands, etc.)",
      "Microphones",
    ],
    includesEs: [
      '2 Medios 15" (bocinas)',
      '2 Bajos 18"',
      "2 Cabezas móviles beam",
      "2 Cabezas móviles wash",
      "2 Torres iluminación lambrin",
      "DJ Versátil / STAFF",
      "Souvenirs (Globos, corbatas, varitas etc.)",
      "Micrófonos",
    ],
    variants: [
      { label: "Without screens", labelEs: "Sin pantallas", price: 8140 },
      { label: 'With 55" screens', labelEs: 'Con pantallas 55"', price: 11000 },
    ],
    tier: "mid",
    image: "/images/service-audio.jpg",
  },
  {
    id: "black",
    name: "Black",
    nameEs: "Black",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 9900,
    duration: "5 hrs",
    durationEs: "5 hrs",
    includes: [
      '2x 15" speakers',
      '2x 18" subwoofers',
      "2 beam moving heads",
      "2 wash moving heads",
      "2 lighting towers",
      "Versatile DJ / Staff",
      "Pixel booth",
      "60cm DJ platform (elevated)",
      "Souvenirs (balloons, ties, wands, etc.)",
      "Microphones",
    ],
    includesEs: [
      '2 Medios 15" (bocinas)',
      '2 Bajos 18"',
      "2 Cabezas móviles beam",
      "2 Cabezas móviles wash",
      "2 Torres para iluminación",
      "DJ Versátil / STAFF",
      "Cabina de pixeles",
      "Tapanco 60 cm Dj en alto",
      "Souvenirs (Globos, corbatas, varitas etc.)",
      "Micrófonos",
    ],
    tier: "mid",
    featured: true,
    image: "/images/service-audio.jpg",
  },
  {
    id: "luxury-petite",
    name: "Luxury Petite",
    nameEs: "Luxury Petite",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 17600,
    duration: "6 hrs",
    durationEs: "6 hrs",
    includes: [
      "2 speakers (audio)",
      "2 moving heads",
      '2x 18" subwoofers',
      "DJ and Staff",
      "Custom booth",
      "Souvenirs (headbands, balloons, ties, wands, etc.)",
      "Wireless microphones",
      "5x5 custom dance floor, 3 designs to choose from (FULL HD)",
      "50cm raised DJ platform",
    ],
    includesEs: [
      "2 medios (audio)",
      "2 Cabezas moviles",
      '2 Subwofer de 18"',
      "DJ y STAFF",
      "Cabina personalizada",
      "Souvenirs (Diademas Globos, corbatas, varitas etc.)",
      "Micrófonos inalambricos",
      "Pista 5x5 personalizada, 3 propuestas a elegir con diseñadora imagen FULL HD",
      "Templete para DJ a 50 cm de altura",
    ],
    tier: "premium",
    image: "/images/service-experiences.jpg",
  },
  {
    id: "fancy",
    name: "Fancy",
    nameEs: "Fancy",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 17600,
    duration: "6 hrs",
    durationEs: "6 hrs",
    includes: [
      "Pitch 3x1 LED screen",
      "60cm raised platform",
      "DJ / Staff",
      '2x 15" speakers',
      '2x 18" subwoofers',
      "Event hosting",
      "4 moving heads",
      "4 LED cannons",
      "Microphones",
      "3 custom visuals",
      "Souvenirs (headbands, balloons, ties, wands, etc.)",
      "4 cold spark machines",
      "LED robot on stilts show OR Bad Bunny / Luis Miguel mascot show",
    ],
    includesEs: [
      "Pantalla Pitch 3 x 1",
      "Tapanco 60 cm",
      "DJ // STAFF",
      '2 Medios de 15" (bocinas)',
      '2 Bajos 18"',
      "Animación de evento",
      "4 Cabezas móviles",
      "4 Cañones Led",
      "Micrófonos",
      "3 visuales personalizados",
      "Souvenirs (Diademas Globos, corbatas, varitas etc)",
      "4 chisperos",
      "Show robot led en zancos o show cabezonas BAD Bunny O Luis Miguel",
    ],
    tier: "premium",
    featured: true,
    image: "/images/service-experiences.jpg",
  },
  {
    id: "luxury",
    name: "Luxury",
    nameEs: "Luxury",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 30800,
    duration: "6 hrs",
    durationEs: "6 hrs",
    includes: [
      "Pitch 3x2 LED screen",
      "DJ platform",
      "Versatile DJ / Staff",
      '4x 15" speakers',
      '4x 15" subwoofers',
      "4-point lighting structures",
      "2 beam moving heads",
      "2 wash moving heads",
      "8 LED cannons",
      "Wireless microphones",
      "VIP souvenirs",
      "1 fog machine",
      "Robot show, Luis Miguel or Bad Bunny",
      "8 cold pyrotechnic detonations",
      "3 custom visuals",
      "Confetti bazooka",
      "White DJ booth",
    ],
    includesEs: [
      "Pantalla Pitch 3 x 2",
      "Templete dj",
      "DJ Versátil / STAFF",
      '4 medios de 15"',
      '4 Bajos 15"',
      "Estructuras, iluminación 4 puntos",
      "2 Cabezas móviles",
      "2 Cabezas móviles wash",
      "8 Cañones Led",
      "Micrófonos inalambricos",
      "Souvenirs VIP",
      "1 Máquina de humo",
      "Show Robot, Luis Miguel o Bad bunny",
      "8 Detonaciones de pirotecnia fría",
      "3 Visuales personalizados",
      "Bazooka de papelitos",
      "Cabina DJ booth blanco",
    ],
    tier: "luxury",
    image: "/images/portfolio-party.jpg",
  },
  {
    id: "gold-bar",
    name: "Gold Bar",
    nameEs: "Gold Bar",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 36300,
    duration: "6 hrs",
    durationEs: "6 hrs",
    includes: [
      "Pitch 3x2 LED screen",
      "DJ platform",
      "Versatile DJ / Staff",
      '4x 15" speakers',
      '4x 15" subwoofers',
      "4-point lighting structures",
      "4 beam moving heads",
      "4 wash moving heads",
      "8 LED cannons",
      "Wireless microphones",
      "VIP souvenirs",
      "1 fog machine",
      "Robot show, Luis Miguel or Bad Bunny",
      "8 cold pyrotechnic detonations",
      "3 custom visuals",
      "Confetti bazooka",
      "Premium drink bar",
      "2 bartenders",
      "Ice cooler",
      "Cocktail elements",
    ],
    includesEs: [
      "Pantalla Pitch 3 x 2",
      "Templete dj",
      "DJ Versátil / STAFF",
      '4 medios de 15"',
      '4 Bajos 15"',
      "Estructuras, iluminación 4 puntos",
      "4 Cabezas móviles",
      "4 Cabezas móviles wash",
      "8 Cañones Led",
      "Micrófonos inalambricos",
      "Souvenirs VIP",
      "1 Máquina de humo",
      "Show Robot, Luis Miguel o Bad bunny",
      "8 Detonaciones de pirotecnia fría",
      "3 Visuales personalizados",
      "Bazooka de papelitos",
      "Barra de bebidas",
      "2 Bartenders",
      "Hielera",
      "Elementos de cocteleria",
    ],
    tier: "luxury",
    featured: true,
    image: "/images/portfolio-bar.jpg",
  },
  {
    id: "sweet-dream",
    name: "Sweet Dream",
    nameEs: "Sweet Dream",
    category: "audio-dj",
    categoryLabel: "Audio & DJ",
    categoryLabelEs: "Audio & DJ",
    price: 46200,
    duration: "7 hrs",
    durationEs: "7 hrs",
    includes: [
      "Pitch 3x2 LED screen",
      "DJ platform",
      "Versatile DJ / Staff",
      '4x 15" speakers',
      '4x 15" subwoofers',
      "4-point lighting structures",
      "4 beam moving heads",
      "4 wash moving heads",
      "8 LED cannons",
      "Wireless microphones",
      "VIP souvenirs",
      "1 fog machine",
      "Robot show, Luis Miguel or Bad Bunny",
      "8 cold pyrotechnic detonations",
      "3 custom visuals",
      "Custom booth, 3 designs to choose from (FULL HD)",
    ],
    includesEs: [
      "Pantalla Pitch 3 x 2",
      "Templete dj",
      "DJ Versátil / STAFF",
      '4 medios de 15"',
      '4 Bajos 15"',
      "Estructuras, iluminación 4 puntos",
      "4 Cabezas móviles",
      "4 Cabezas móviles wash",
      "8 Cañones Led",
      "Micrófonos inalambricos",
      "Souvenirs VIP",
      "1 Máquina de humo",
      "Show Robot, Luis Miguel o Bad bunny",
      "8 Detonaciones de pirotecnia fría",
      "3 Visuales personalizados",
      "Cabina personalizada, 3 propuestas a elegir con diseñadora imagen FULL HD",
    ],
    tier: "luxury",
    image: "/images/portfolio-wedding.jpg",
  },

  // ── Special Effects ──
  {
    id: "fire-machine",
    name: "Fire Machine",
    nameEs: "Máquina de fuego",
    category: "special-effects",
    categoryLabel: "Special Effects",
    categoryLabelEs: "Efectos Especiales",
    price: 990,
    duration: "1 hr",
    durationEs: "1 hr",
    includes: ["1 cartridge with 30 shots", "Operator", "Transport"],
    includesEs: ["1 cartucho con 30 disparos", "Operador", "Traslado"],
    image: "/images/service-atmosphere.jpg",
  },
  {
    id: "cold-spark",
    name: "Cold Spark",
    nameEs: "Chispero",
    category: "special-effects",
    categoryLabel: "Special Effects",
    categoryLabelEs: "Efectos Especiales",
    price: 385,
    duration: "15 sec",
    durationEs: "15 seg",
    includes: ["1 detonation of 15 seconds"],
    includesEs: ["1 detonación de 15 segundos"],
    image: "/images/service-atmosphere.jpg",
  },
  {
    id: "fog-machine",
    name: "Fog Machine",
    nameEs: "Máquina de Humo",
    category: "special-effects",
    categoryLabel: "Special Effects",
    categoryLabelEs: "Efectos Especiales",
    price: 825,
    duration: "1 hr",
    durationEs: "1 hr",
    includes: ["Professional fog machine"],
    includesEs: ["Máquina de humo profesional"],
    image: "/images/service-atmosphere.jpg",
  },

  // ── Shows ──
  {
    id: "robot-led",
    name: "LED Robot",
    nameEs: "Robot LED",
    category: "shows",
    categoryLabel: "Shows",
    categoryLabelEs: "Shows",
    price: 2145,
    duration: "45 min",
    durationEs: "45 min",
    includes: ["45 min show synchronized with DJ music"],
    includesEs: [
      "45 mn de show acompañado de la música sincronizada con el dj",
    ],
    image: "/images/service-experiences.jpg",
  },

  // ── Decor ──
  {
    id: "giant-letters",
    name: "Giant Letters",
    nameEs: "Letras Gigantes",
    category: "decor",
    categoryLabel: "Decor",
    categoryLabelEs: "Decoración",
    price: 935,
    duration: "Full event",
    durationEs: "Evento completo",
    includes: ["Models: Smooth, bulb, and bubble", "Installation", "Transport"],
    includesEs: ["Modelos: Lisa, focos y burbuja", "Instalación", "Traslado"],
    image: "/images/service-decor.jpg",
  },
]

export const CATEGORY_INFO: Record<
  ServiceCategory,
  { label: string; labelEs: string; description: string; descriptionEs: string; image: string }
> = {
  "audio-dj": {
    label: "Audio & DJ Packages",
    labelEs: "Paquetes Audio & DJ",
    description: "Complete production packages with professional sound, lighting, and DJ entertainment",
    descriptionEs: "Paquetes completos de producción con sonido profesional, iluminación y entretenimiento DJ",
    image: "/images/service-audio.jpg",
  },
  "special-effects": {
    label: "Special Effects",
    labelEs: "Efectos Especiales",
    description: "Fire machines, cold sparks, fog, and pyrotechnic effects",
    descriptionEs: "Máquinas de fuego, chisperos, humo y efectos pirotécnicos",
    image: "/images/service-atmosphere.jpg",
  },
  shows: {
    label: "Shows & Entertainment",
    labelEs: "Shows y Entretenimiento",
    description: "LED robot shows and live entertainment performances",
    descriptionEs: "Shows de robot LED y entretenimiento en vivo",
    image: "/images/service-experiences.jpg",
  },
  decor: {
    label: "Decor & Accessories",
    labelEs: "Decoración y Accesorios",
    description: "Giant letters, custom elements, and decorative installations",
    descriptionEs: "Letras gigantes, elementos personalizados e instalaciones decorativas",
    image: "/images/service-decor.jpg",
  },
}
