export interface CatalogItem {
  id: string
  name: string
  category: string
  description: string
  price: string
  priceValue: number
  unit: string
  image: string
  serviceHours?: string
  includes?: string[]
}

export interface CatalogCategory {
  id: string
  name: string
  description: string
  icon: string
  items: CatalogItem[]
}

export const catalog: CatalogCategory[] = [
  {
    id: "paquetes-dj",
    name: "Paquetes DJ & Audio",
    description:
      "Paquetes completos con DJ profesional, audio premium e iluminacion de alto nivel para cualquier tipo de evento.",
    icon: "music",
    items: [
      {
        id: "magic",
        name: "Magic",
        category: "Paquetes DJ & Audio",
        description:
          "2 medios 15\" (bocinas), iluminacion LED, DJ Versatil/STAFF, microfono, tripies. Cabina a elegir: blanca paneles, blanca vintage o Talavera.",
        price: "$6,500 MXN",
        priceValue: 6500,
        unit: "evento",
        serviceHours: "5 hrs servicio continuo",
        includes: ["2 medios 15\" (bocinas)", "Iluminacion LED", "DJ Versatil / STAFF", "Microfono", "Tripies", "Cabina a elegir"],
        image: "/images/catalog/dj-magic.jpg",
      },
      {
        id: "magic-pixeles",
        name: "Magic Pixeles",
        category: "Paquetes DJ & Audio",
        description:
          "2 medios 15\" (bocinas), iluminacion LED, DJ/Versatil/STAFF, cabina pixeles iluminada, 2 cabezas moviles beam, 2 torres iluminacion, microfonos, conduccion del evento, souvenirs.",
        price: "$8,184 MXN",
        priceValue: 8184,
        unit: "evento",
        serviceHours: "5 hrs servicio continuo",
        includes: ["2 medios 15\" (bocinas)", "Iluminacion LED", "DJ / Versatil / STAFF", "Cabina Pixeles iluminada", "2 Cabezas moviles beam", "2 Torres para Iluminacion", "Microfonos", "Conduccion del evento", "Souvenirs (Globos, corbatas, varitas etc.)"],
        image: "/images/catalog/dj-magic-pixels.jpg",
      },
      {
        id: "party",
        name: "Party",
        category: "Paquetes DJ & Audio",
        description:
          "2 medios 15\" (bocinas), 2 bajos 18\", 2 cabezas moviles beam, 2 cabezas moviles wash, 2 torres iluminacion lambrin, DJ Versatil/STAFF, souvenirs, microfonos.",
        price: "$9,768 MXN",
        priceValue: 9768,
        unit: "evento",
        serviceHours: "5 hrs servicio continuo",
        includes: ["2 Medios 15\" (bocinas)", "2 Bajos 18\"", "2 Cabezas moviles beam", "2 Cabezas moviles wash", "2 Torres iluminacion lambrin", "DJ Versatil / STAFF", "Souvenirs (Globos, corbatas, varitas etc.)", "Microfonos"],
        image: "/images/catalog/dj-party.jpg",
      },
      {
        id: "party-pantallas",
        name: "Party con Pantallas 55\"",
        category: "Paquetes DJ & Audio",
        description:
          "Paquete Party completo con pantallas de 55 pulgadas para visuales impactantes.",
        price: "$13,200 MXN",
        priceValue: 13200,
        unit: "evento",
        serviceHours: "5 hrs servicio continuo",
        includes: ["Todo lo del paquete Party", "Pantallas de 55\""],
        image: "/images/catalog/dj-party-screens.jpg",
      },
      {
        id: "black",
        name: "Black",
        category: "Paquetes DJ & Audio",
        description:
          "2 medios 15\" (bocinas), 2 bajos 18\", 2 cabezas moviles beam, 2 cabezas moviles wash, 2 torres iluminacion, DJ Versatil/STAFF, cabina de pixeles, tapanco 60 cm DJ en alto, souvenirs, microfonos.",
        price: "$11,880 MXN",
        priceValue: 11880,
        unit: "evento",
        serviceHours: "5 hrs servicio continuo",
        includes: ["2 Medios 15\" (bocinas)", "2 Bajos 18\"", "2 Cabezas moviles beam", "2 Cabezas moviles wash", "2 Torres para iluminacion", "DJ Versatil / STAFF", "Cabina de pixeles", "Tapanco 60 cm Dj en alto", "Souvenirs", "Microfonos"],
        image: "/images/catalog/dj-black.jpg",
      },
      {
        id: "luxury-petite",
        name: "Luxury Petite",
        category: "Paquetes DJ & Audio",
        description:
          "2 medios (audio), 2 cabezas moviles, 2 subwoofer de 18\", DJ y STAFF, cabina personalizada, souvenirs, microfonos inalambricos, pista 5x5 personalizada con 3 propuestas a elegir, templete para DJ a 50 cm de altura.",
        price: "$21,120 MXN",
        priceValue: 21120,
        unit: "evento",
        serviceHours: "6 hrs servicio continuo",
        includes: ["2 medios (audio)", "2 Cabezas moviles", "2 Subwofer de 18\"", "DJ y STAFF", "Cabina personalizada", "Souvenirs (Diademas, Globos, corbatas, varitas etc.)", "Microfonos inalambricos", "Pista 5x5 personalizada, 3 propuestas a elegir con disenadora imagen FULL HD", "Templete para DJ a 50 cm de altura"],
        image: "/images/catalog/dj-luxury-petite.jpg",
      },
      {
        id: "fancy",
        name: "Fancy",
        category: "Paquetes DJ & Audio",
        description:
          "Pantalla Pitch 3x1, tapanco 60 cm, DJ/STAFF, 2 medios 15\", 2 bajos 18\", animacion de evento, 4 cabezas moviles, 4 canones LED, microfonos, 3 visuales personalizados, souvenirs, 4 chisperos, show robot LED o show cabezonas.",
        price: "$21,120 MXN",
        priceValue: 21120,
        unit: "evento",
        serviceHours: "6 hrs servicio continuo",
        includes: ["Pantalla Pitch 3 x 1", "Tapanco 60 cm", "DJ // STAFF", "2 Medios de 15\" (bocinas)", "2 Bajos 18\"", "Animacion de evento", "4 Cabezas moviles", "4 Canones Led", "Microfonos", "3 visuales personalizados", "Souvenirs", "4 chisperos", "Show robot led en zancos o show cabezonas BAD Bunny o Luis Miguel"],
        image: "/images/catalog/dj-fancy.jpg",
      },
      {
        id: "luxury",
        name: "Luxury",
        category: "Paquetes DJ & Audio",
        description:
          "Pantalla Pitch 3x2, templete DJ, DJ Versatil/STAFF, 4 medios 15\", 4 bajos 15\", estructuras iluminacion 4 puntos, 2 cabezas moviles, 2 cabezas moviles wash, 8 canones LED, microfonos inalambricos, souvenirs VIP, maquina de humo, show robot, 8 detonaciones pirotecnia fria, 3 visuales personalizados, bazooka de papelitos, cabina DJ booth blanco.",
        price: "$36,960 MXN",
        priceValue: 36960,
        unit: "evento",
        serviceHours: "6 hrs servicio continuo",
        includes: ["Pantalla Pitch 3 x 2", "Templete dj", "DJ Versatil /STAFF", "4 medios de 15\"", "4 Bajos 15\"", "Estructuras, iluminacion 4 puntos", "2 Cabezas moviles", "2 Cabezas moviles wash", "8 Canones Led", "Microfonos inalambricos", "Souvenirs VIP", "1 Maquina de humo", "Show Robot, Luis Miguel o Bad bunny", "8 Detonaciones de pirotecnia fria", "3 Visuales personalizados", "Bazooka de papelitos", "Cabina DJ booth blanco"],
        image: "/images/catalog/dj-luxury.jpg",
      },
      {
        id: "gold-bar",
        name: "Gold Bar",
        category: "Paquetes DJ & Audio",
        description:
          "Todo lo del paquete Luxury mas: barra de bebidas, 2 bartenders, hielera, elementos de cocteleria.",
        price: "$43,560 MXN",
        priceValue: 43560,
        unit: "evento",
        serviceHours: "6 hrs servicio continuo",
        includes: ["Todo lo del paquete Luxury", "Barra de bebidas", "2 Bartenders", "Hielera", "Elementos de cocteleria"],
        image: "/images/catalog/dj-gold-bar.jpg",
      },
      {
        id: "sweet-dream",
        name: "Sweet Dream",
        category: "Paquetes DJ & Audio",
        description:
          "El paquete mas completo con cabina personalizada, pista de baile 5x5 con diseno en conjunto con pantalla, creando una sola pieza.",
        price: "$55,440 MXN",
        priceValue: 55440,
        unit: "evento",
        serviceHours: "7 hrs servicio continuo",
        includes: ["Pantalla Pitch 3 x 2", "Templete dj", "DJ Versatil /STAFF", "4 medios de 15\"", "4 Bajos 15\"", "Estructuras, iluminacion 4 puntos", "4 Cabezas moviles", "4 Cabezas moviles wash", "8 Canones Led", "Microfonos inalambricos", "Souvenirs VIP", "1 Maquina de humo", "Show Robot, Luis Miguel o Bad bunny", "8 Detonaciones de pirotecnia fria", "3 Visuales personalizados", "Cabina personalizada, 3 propuestas a elegir con disenadora imagen FULL HD"],
        image: "/images/catalog/dj-sweet-dream.jpg",
      },
      {
        id: "luxury-gold-incluye-salon",
        name: "Paquete Luxury Gold (Incluye Salon)",
        category: "Paquetes DJ & Audio",
        description:
          "Audio con barra de bebidas personalizada, pista personalizada, barra de bebidas y alcohol ilimitado, mobiliario crossback y mesas, vajilla negra o a elegir, meseros y barmans, refresco y hielo ilimitado, servicio de corte de espada o menu 3 tiempos, coctel de bienvenida, centros de mesa, hostess/recepcion, tornaboda (esquites, maruchan o chilaquiles), kit anticruda.",
        price: "$1,650 MXN",
        priceValue: 1650,
        unit: "por persona (min. 60 personas)",
        serviceHours: "Evento completo",
        includes: ["Salon incluido", "Audio con barra de bebidas personalizada", "Pista personalizada", "Barra de bebidas y alcohol ilimitado", "Mobiliario crossback y mesas", "Vajilla negra o a elegir", "Meseros y barmans", "Refresco y hielo ilimitado", "Servicio de corte de espada o menu 3 tiempos", "Coctel de bienvenida", "Centros de mesa", "Hostess / Recepcion", "Tornaboda: esquites, maruchan o chilaquiles", "Kit anticruda"],
        image: "/images/catalog/dj-luxury-gold.jpg",
      },
    ],
  },
  {
    id: "efectos-especiales",
    name: "Efectos Especiales",
    description:
      "Fuego, CO2, chisperos, humo, laser y confeti. Momentos clave que dejan a todos sin aliento.",
    icon: "flame",
    items: [
      {
        id: "maquina-fuego",
        name: "Maquina de Fuego",
        category: "Efectos Especiales",
        description:
          "1 cartucho con 30 disparos, operador y traslado incluidos.",
        price: "$990 MXN",
        priceValue: 990,
        unit: "c/u por hora de servicio",
        image: "/images/catalog/fx-fire.jpg",
      },
      {
        id: "chispero",
        name: "Chispero",
        category: "Efectos Especiales",
        description:
          "1 detonacion de 15 segundos de pirotecnia fria controlada.",
        price: "$385 MXN",
        priceValue: 385,
        unit: "por detonacion",
        image: "/images/catalog/fx-sparkler.jpg",
      },
      {
        id: "maquina-co2-plata",
        name: "Maquina CO2 (Papel Plata)",
        category: "Efectos Especiales",
        description:
          "2 descargas de CO2 con papel plata. Incluye operador, 1 hora de servicio y traslado.",
        price: "$2,200 MXN",
        priceValue: 2200,
        unit: "por hora",
        image: "/images/catalog/fx-co2.jpg",
      },
      {
        id: "papel-mariposa",
        name: "Papel Mariposa (extra)",
        category: "Efectos Especiales",
        description:
          "Efecto de papel mariposa para la maquina CO2.",
        price: "$660 MXN",
        priceValue: 660,
        unit: "extra",
        image: "/images/catalog/fx-butterfly.jpg",
      },
      {
        id: "papel-color",
        name: "Papel de Color (extra)",
        category: "Efectos Especiales",
        description:
          "Papel de colores personalizados para la maquina CO2.",
        price: "$770 MXN",
        priceValue: 770,
        unit: "extra",
        image: "/images/catalog/fx-confetti.jpg",
      },
      {
        id: "maquina-humo",
        name: "Maquina de Humo",
        category: "Efectos Especiales",
        description:
          "Humo atmosferico para crear ambientes misteriosos y dramaticos.",
        price: "$825 MXN",
        priceValue: 825,
        unit: "por evento",
        image: "/images/catalog/fx-smoke.jpg",
      },
      {
        id: "aro-laser",
        name: "Aro Laser",
        category: "Efectos Especiales",
        description:
          "Incluye maquina de humo, laser de 5 watts y operador.",
        price: "$3,300 MXN",
        priceValue: 3300,
        unit: "por evento",
        image: "/images/catalog/fx-laser.jpg",
      },
      {
        id: "pirotecnia-fireworks",
        name: "Paquete Fireworks",
        category: "Efectos Especiales",
        description:
          "Paquete de bombas y chisperos a 50 metros de altura, duracion 2 minutos.",
        price: "$7,150 MXN",
        priceValue: 7150,
        unit: "por show",
        image: "/images/catalog/fx-fireworks.jpg",
      },
    ],
  },
  {
    id: "shows",
    name: "Shows en Vivo",
    description:
      "Robot LED interactivo, show de Luis Miguel y shows de drones con figuras personalizadas.",
    icon: "zap",
    items: [
      {
        id: "robot-led",
        name: "Robot LED",
        category: "Shows en Vivo",
        description:
          "45 minutos de show acompanado de la musica sincronizada con el DJ.",
        price: "$2,145 MXN",
        priceValue: 2145,
        unit: "por show",
        image: "/images/catalog/show-robot.jpg",
      },
      {
        id: "show-luis-miguel",
        name: "Show de Luis Miguel",
        category: "Shows en Vivo",
        description:
          "40 minutos en 2 lapsos de 20 min. Acompanado de la musica sincronizada con el DJ, tequila preparado en azulito, mochila especial para repartir shots.",
        price: "$1,980 MXN",
        priceValue: 1980,
        unit: "por show",
        image: "/images/catalog/show-luismi.jpg",
      },
      {
        id: "letras-gigantes",
        name: "Letras Gigantes",
        category: "Shows en Vivo",
        description:
          "Modelos: Lisa, focos y burbuja. Incluye instalacion y traslado.",
        price: "$935 MXN",
        priceValue: 935,
        unit: "c/u",
        image: "/images/catalog/show-letters.jpg",
      },
      {
        id: "show-drones",
        name: "Show de Drones",
        category: "Shows en Vivo",
        description:
          "Shows aereos personalizables para cualquier tipo de evento. Figuras como corazon, anillo, copa o 2 letras. Cumplimos todos los requisitos legales y de seguridad.",
        price: "$6,000 MXN",
        priceValue: 6000,
        unit: "c/u figura (min. 20 drones)",
        image: "/images/catalog/show-drones.jpg",
      },
    ],
  },
  {
    id: "pistas-baile",
    name: "Pistas de Baile",
    description:
      "Pistas de pixeles LED, pistas blancas con iniciales en vinil y pistas personalizadas HD.",
    icon: "disc",
    items: [
      {
        id: "pista-pixeles-4x4",
        name: "Pista Pixeles 4x4m (9 modulos)",
        category: "Pistas de Baile",
        description:
          "Pista de pixeles LED de 4x4 metros con efectos interactivos y reactivos a la musica.",
        price: "$5,500 MXN",
        priceValue: 5500,
        unit: "por evento",
        image: "/images/catalog/floor-pixel.jpg",
      },
      {
        id: "pista-pixeles-4x5",
        name: "Pista Pixeles 4x5m (12 modulos)",
        category: "Pistas de Baile",
        description:
          "Pista de pixeles LED de 4x5 metros.",
        price: "$7,150 MXN",
        priceValue: 7150,
        unit: "por evento",
        image: "/images/catalog/floor-pixel.jpg",
      },
      {
        id: "pista-pixeles-5x5",
        name: "Pista Pixeles 5x5m (16 modulos)",
        category: "Pistas de Baile",
        description:
          "Pista de pixeles LED de 5x5 metros.",
        price: "$9,350 MXN",
        priceValue: 9350,
        unit: "por evento",
        image: "/images/catalog/floor-pixel.jpg",
      },
      {
        id: "pista-pixeles-6x5",
        name: "Pista Pixeles 6x5m (20 modulos)",
        category: "Pistas de Baile",
        description:
          "Pista de pixeles LED de 6x5 metros, ideal para eventos grandes.",
        price: "$12,100 MXN",
        priceValue: 12100,
        unit: "por evento",
        image: "/images/catalog/floor-pixel-large.jpg",
      },
      {
        id: "pista-blanca-4x4",
        name: "Pista Blanca con Iniciales 4x4m",
        category: "Pistas de Baile",
        description:
          "Pista blanca elegante de 4x4 metros con iniciales en vinil.",
        price: "$3,960 MXN",
        priceValue: 3960,
        unit: "por evento",
        image: "/images/catalog/floor-white.jpg",
      },
      {
        id: "pista-blanca-4x5",
        name: "Pista Blanca con Iniciales 4x5m",
        category: "Pistas de Baile",
        description:
          "Pista blanca elegante de 4x5 metros con iniciales en vinil.",
        price: "$5,280 MXN",
        priceValue: 5280,
        unit: "por evento",
        image: "/images/catalog/floor-white.jpg",
      },
      {
        id: "pista-blanca-5x5",
        name: "Pista Blanca con Iniciales 5x5m",
        category: "Pistas de Baile",
        description:
          "Pista blanca elegante de 5x5 metros con iniciales en vinil.",
        price: "$7,040 MXN",
        priceValue: 7040,
        unit: "por evento",
        image: "/images/catalog/floor-white.jpg",
      },
      {
        id: "pista-blanca-6x5",
        name: "Pista Blanca con Iniciales 6x5m",
        category: "Pistas de Baile",
        description:
          "Pista blanca elegante de 6x5 metros con iniciales en vinil.",
        price: "$8,800 MXN",
        priceValue: 8800,
        unit: "por evento",
        image: "/images/catalog/floor-white-large.jpg",
      },
      {
        id: "pista-personalizada-4x4",
        name: "Pista Personalizada HD 4x4m",
        category: "Pistas de Baile",
        description:
          "Pista FULL HD con 3 propuestas a elegir con disenadora.",
        price: "$5,500 MXN",
        priceValue: 5500,
        unit: "por evento",
        image: "/images/catalog/floor-custom.jpg",
      },
      {
        id: "pista-personalizada-6x5",
        name: "Pista Personalizada HD 6x5m",
        category: "Pistas de Baile",
        description:
          "Pista FULL HD con 3 propuestas a elegir con disenadora.",
        price: "$12,100 MXN",
        priceValue: 12100,
        unit: "por evento",
        image: "/images/catalog/floor-custom.jpg",
      },
    ],
  },
  {
    id: "iluminacion",
    name: "Iluminacion Arquitectonica",
    description:
      "Iluminacion puntual aerea en carpas, jardines, muros y pilares con tecnologia IP65.",
    icon: "zap",
    items: [
      {
        id: "canon-iluminacion-calido",
        name: "Canon Iluminacion (Calido/Ambar/Frio)",
        category: "Iluminacion Arquitectonica",
        description:
          "Iluminacion puntual aerea en carpas a 4 puntos o mas. Montaje y desmontaje incluidos. Colores calidos, ambar, luz fria o color a elegir.",
        price: "$935 MXN",
        priceValue: 935,
        unit: "c/u",
        image: "/images/catalog/light-canon.jpg",
      },
      {
        id: "canon-ip65-exterior",
        name: "Canon LED IP65 (Exterior)",
        category: "Iluminacion Arquitectonica",
        description:
          "Iluminacion arquitectonica con enfoque meticuloso para resaltar jardines, muros, pilares. Tecnologia IP65 resistente al agua.",
        price: "$600 MXN",
        priceValue: 600,
        unit: "c/u",
        image: "/images/catalog/light-ip65.jpg",
      },
    ],
  },
  {
    id: "mobiliario",
    name: "Renta de Sillas",
    description:
      "Sillas elegantes para bodas y eventos: Tiffany, Chanel, Crossback, Thonik y mas.",
    icon: "armchair",
    items: [
      {
        id: "silla-tiffany",
        name: "Silla Tiffany",
        category: "Renta de Sillas",
        description:
          "Silla Tiffany clasica, ideal para bodas y eventos elegantes.",
        price: "$38.50 MXN",
        priceValue: 38.5,
        unit: "por unidad",
        image: "/images/catalog/chair-tiffany.jpg",
      },
      {
        id: "silla-tiffany-blanca",
        name: "Silla Tiffany Blanca",
        category: "Renta de Sillas",
        description:
          "Silla Tiffany en acabado blanco elegante.",
        price: "$38.50 MXN",
        priceValue: 38.5,
        unit: "por unidad",
        image: "/images/catalog/chair-tiffany-white.jpg",
      },
      {
        id: "silla-chanel",
        name: "Silla Chanel (Dorada/Negra)",
        category: "Renta de Sillas",
        description:
          "Silla Chanel en acabado dorado o negro. Disponible en 300 unidades.",
        price: "$44 MXN",
        priceValue: 44,
        unit: "por unidad",
        image: "/images/catalog/chair-chanel.jpg",
      },
      {
        id: "silla-crossback",
        name: "Silla Crossback",
        category: "Renta de Sillas",
        description:
          "Silla Crossback de madera con respaldo cruzado. Estilo rustico-chic.",
        price: "$82.50 MXN",
        priceValue: 82.5,
        unit: "por unidad",
        image: "/images/catalog/chair-crossback.jpg",
      },
      {
        id: "silla-thonik",
        name: "Silla Thonik (Rosa/Azul/Blanco)",
        category: "Renta de Sillas",
        description:
          "Silla Thonik de diseno contemporaneo. Disponible en rosa, azul y blanco.",
        price: "$132 MXN",
        priceValue: 132,
        unit: "por unidad",
        image: "/images/catalog/chair-thonik.jpg",
      },
      {
        id: "silla-sewing",
        name: "Silla Sewing",
        category: "Renta de Sillas",
        description:
          "Silla Sewing premium de alta gama.",
        price: "$154 MXN",
        priceValue: 154,
        unit: "por unidad",
        image: "/images/catalog/chair-sewing.jpg",
      },
    ],
  },
  {
    id: "mesas",
    name: "Renta de Mesas",
    description:
      "Mesas cuadradas y redondas para eventos de cualquier tamano.",
    icon: "armchair",
    items: [
      {
        id: "mesa-cuadrada",
        name: "Mesa Cuadrada",
        category: "Renta de Mesas",
        description:
          "Mesa cuadrada elegante para eventos.",
        price: "$610 MXN",
        priceValue: 610,
        unit: "c/u",
        image: "/images/catalog/table-square.jpg",
      },
      {
        id: "mesa-redonda-12",
        name: "Mesa Redonda (12 personas)",
        category: "Renta de Mesas",
        description:
          "Mesa redonda para 12 personas.",
        price: "$627 MXN",
        priceValue: 627,
        unit: "c/u",
        image: "/images/catalog/table-round.jpg",
      },
      {
        id: "mesa-redonda-10",
        name: "Mesa Redonda (10 personas)",
        category: "Renta de Mesas",
        description:
          "Mesa redonda para 10 personas.",
        price: "$550 MXN",
        priceValue: 550,
        unit: "c/u",
        image: "/images/catalog/table-round.jpg",
      },
    ],
  },
  {
    id: "loza",
    name: "Renta de Loza",
    description:
      "Platos y sobreplatos elegantes para servicio de banquetes.",
    icon: "utensils",
    items: [
      {
        id: "plato-trinche-negro",
        name: "Plato Trinche Negro",
        category: "Renta de Loza",
        description: "Plato trinche en acabado negro elegante.",
        price: "$22 MXN",
        priceValue: 22,
        unit: "por unidad",
        image: "/images/catalog/plate-black.jpg",
      },
      {
        id: "plato-cuadrado",
        name: "Plato Cuadrado",
        category: "Renta de Loza",
        description: "Plato cuadrado moderno.",
        price: "$16 MXN",
        priceValue: 16,
        unit: "por unidad",
        image: "/images/catalog/plate-square.jpg",
      },
      {
        id: "plato-economico",
        name: "Plato Economico",
        category: "Renta de Loza",
        description: "Plato economico para eventos con presupuesto ajustado.",
        price: "$11 MXN",
        priceValue: 11,
        unit: "por unidad",
        image: "/images/catalog/plate-basic.jpg",
      },
      {
        id: "sobreplato-vidrio",
        name: "Sobreplato de Vidrio",
        category: "Renta de Loza",
        description: "Sobreplato de vidrio transparente.",
        price: "$18 MXN",
        priceValue: 18,
        unit: "por unidad",
        image: "/images/catalog/plate-glass.jpg",
      },
      {
        id: "sobreplato",
        name: "Sobreplato",
        category: "Renta de Loza",
        description: "Sobreplato elegante.",
        price: "$20 MXN",
        priceValue: 20,
        unit: "c/u",
        image: "/images/catalog/charger.jpg",
      },
    ],
  },
  {
    id: "cubiertos",
    name: "Renta de Cubiertos",
    description:
      "Cubiertos estandar y dorados para eventos elegantes.",
    icon: "utensils",
    items: [
      {
        id: "cuchara",
        name: "Cuchara",
        category: "Renta de Cubiertos",
        description: "Cuchara estandar.",
        price: "$8 MXN",
        priceValue: 8,
        unit: "por unidad",
        image: "/images/catalog/cutlery-spoon.jpg",
      },
      {
        id: "cuchillo",
        name: "Cuchillo",
        category: "Renta de Cubiertos",
        description: "Cuchillo estandar.",
        price: "$8 MXN",
        priceValue: 8,
        unit: "por unidad",
        image: "/images/catalog/cutlery-knife.jpg",
      },
      {
        id: "tenedor",
        name: "Tenedor",
        category: "Renta de Cubiertos",
        description: "Tenedor estandar.",
        price: "$8 MXN",
        priceValue: 8,
        unit: "por unidad",
        image: "/images/catalog/cutlery-fork.jpg",
      },
      {
        id: "cuchara-dorada",
        name: "Cuchara Dorada",
        category: "Renta de Cubiertos",
        description: "Cuchara en acabado dorado premium.",
        price: "$17 MXN",
        priceValue: 17,
        unit: "por unidad",
        image: "/images/catalog/cutlery-spoon-gold.jpg",
      },
      {
        id: "cuchillo-dorado",
        name: "Cuchillo Dorado",
        category: "Renta de Cubiertos",
        description: "Cuchillo en acabado dorado premium.",
        price: "$17 MXN",
        priceValue: 17,
        unit: "por unidad",
        image: "/images/catalog/cutlery-knife-gold.jpg",
      },
      {
        id: "tenedor-dorado",
        name: "Tenedor Dorado",
        category: "Renta de Cubiertos",
        description: "Tenedor en acabado dorado premium.",
        price: "$17 MXN",
        priceValue: 17,
        unit: "por unidad",
        image: "/images/catalog/cutlery-fork-gold.jpg",
      },
    ],
  },
  {
    id: "cristaleria",
    name: "Renta de Cristaleria",
    description:
      "Vasos, copas y cristaleria fina para bebidas y brindis.",
    icon: "utensils",
    items: [
      {
        id: "vaso-jaibolero",
        name: "Vaso Jaibolero",
        category: "Renta de Cristaleria",
        description: "Vaso alto para bebidas mezcladas.",
        price: "$11 MXN",
        priceValue: 11,
        unit: "por unidad",
        image: "/images/catalog/glass-highball.jpg",
      },
      {
        id: "copa-globo",
        name: "Copa Globo",
        category: "Renta de Cristaleria",
        description: "Copa globo para vino tinto o gin.",
        price: "$15 MXN",
        priceValue: 15,
        unit: "por unidad",
        image: "/images/catalog/glass-globe.jpg",
      },
      {
        id: "copa-margarita",
        name: "Copa Margarita",
        category: "Renta de Cristaleria",
        description: "Copa margarita clasica.",
        price: "$14 MXN",
        priceValue: 14,
        unit: "por unidad",
        image: "/images/catalog/glass-margarita.jpg",
      },
      {
        id: "copa-conaquera",
        name: "Copa Conaquera",
        category: "Renta de Cristaleria",
        description: "Copa conaquera para brandy o cognac.",
        price: "$15 MXN",
        priceValue: 15,
        unit: "por unidad",
        image: "/images/catalog/glass-cognac.jpg",
      },
      {
        id: "copa-champagne",
        name: "Copa Champagne",
        category: "Renta de Cristaleria",
        description: "Copa flauta para champagne y espumosos.",
        price: "$14 MXN",
        priceValue: 14,
        unit: "por unidad",
        image: "/images/catalog/glass-champagne.jpg",
      },
      {
        id: "old-fashion",
        name: "Old Fashion",
        category: "Renta de Cristaleria",
        description: "Vaso old fashion para whisky.",
        price: "$15 MXN",
        priceValue: 15,
        unit: "por unidad",
        image: "/images/catalog/glass-old-fashion.jpg",
      },
      {
        id: "copa-vintage-dorada",
        name: "Copa Vintage Dorada",
        category: "Renta de Cristaleria",
        description: "Copa vintage con acabado dorado.",
        price: "$18 MXN",
        priceValue: 18,
        unit: "por unidad",
        image: "/images/catalog/glass-vintage-gold.jpg",
      },
      {
        id: "copa-vintage-humo",
        name: "Copa Vintage Humo",
        category: "Renta de Cristaleria",
        description: "Copa vintage en tono humo.",
        price: "$18 MXN",
        priceValue: 18,
        unit: "por unidad",
        image: "/images/catalog/glass-vintage-smoke.jpg",
      },
      {
        id: "copa-vintage-colores",
        name: "Copa Vintage (Rosa/Azul/Verde/Arandano)",
        category: "Renta de Cristaleria",
        description: "Copas vintage en colores variados.",
        price: "$18 MXN",
        priceValue: 18,
        unit: "por unidad",
        image: "/images/catalog/glass-vintage-colors.jpg",
      },
    ],
  },
  {
    id: "decoracion",
    name: "Decoracion",
    description:
      "Centros de mesa, candelabros, macrame, herreria y elementos decorativos para tu evento.",
    icon: "star",
    items: [
      {
        id: "centro-mesa-pequeno",
        name: "Centro de Mesa Pequeno",
        category: "Decoracion",
        description: "Centro de mesa tamano pequeno.",
        price: "$495 MXN",
        priceValue: 495,
        unit: "c/u",
        image: "/images/catalog/decor-centerpiece-small.jpg",
      },
      {
        id: "centro-mesa-mediano",
        name: "Centro de Mesa Mediano",
        category: "Decoracion",
        description: "Centro de mesa tamano mediano.",
        price: "$715 MXN",
        priceValue: 715,
        unit: "c/u",
        image: "/images/catalog/decor-centerpiece-medium.jpg",
      },
      {
        id: "centro-mesa-grande",
        name: "Centro de Mesa Grande",
        category: "Decoracion",
        description: "Centro de mesa tamano grande.",
        price: "$935 MXN",
        priceValue: 935,
        unit: "c/u",
        image: "/images/catalog/decor-centerpiece-large.jpg",
      },
      {
        id: "candelabro-3x3",
        name: "Candelabro 3x3",
        category: "Decoracion",
        description: "Candelabro decorativo de 3x3 metros.",
        price: "$13,200 MXN",
        priceValue: 13200,
        unit: "c/u",
        image: "/images/catalog/decor-chandelier.jpg",
      },
      {
        id: "macrame",
        name: "Decoracion Macrame",
        category: "Decoracion",
        description: "Renta de decoracion macrame.",
        price: "$4,400 MXN",
        priceValue: 4400,
        unit: "c/u",
        image: "/images/catalog/decor-macrame.jpg",
      },
      {
        id: "macrame-5-colgantes",
        name: "5 Colgantes Macrame",
        category: "Decoracion",
        description: "5 colgantes macrame. Incluye instalacion y desmontaje. Se requiere 2 dias de montaje previo y un dia posterior para desmontaje.",
        price: "$20,900 MXN",
        priceValue: 20900,
        unit: "paquete",
        image: "/images/catalog/decor-macrame-set.jpg",
      },
      {
        id: "mesa-novios-herreria",
        name: "Mesa de Novios + 2 Sillones (Herreria)",
        category: "Decoracion",
        description: "Mesa de novios con 2 sillones estilo herreria minimalista.",
        price: "$3,960 MXN",
        priceValue: 3960,
        unit: "c/u",
        image: "/images/catalog/decor-sweetheart-table.jpg",
      },
      {
        id: "back-herreria-14-velas",
        name: "2 Back de Herreria con 14 Velas",
        category: "Decoracion",
        description: "Dos piezas de back de herreria con 14 velas en total.",
        price: "$6,600 MXN",
        priceValue: 6600,
        unit: "c/u",
        image: "/images/catalog/decor-back-candles.jpg",
      },
      {
        id: "back-herreria-7-velas",
        name: "1 Back de Herreria con 7 Velas",
        category: "Decoracion",
        description: "Una pieza de back de herreria con 7 velas.",
        price: "$3,850 MXN",
        priceValue: 3850,
        unit: "c/u",
        image: "/images/catalog/decor-back-candles-small.jpg",
      },
      {
        id: "decoracion-flores-natural",
        name: "Decoracion de Flores Natural",
        category: "Decoracion",
        description: "Decoracion con flores naturales.",
        price: "$6,600 MXN",
        priceValue: 6600,
        unit: "c/u",
        image: "/images/catalog/decor-flowers-natural.jpg",
      },
      {
        id: "decoracion-follaje-seco",
        name: "Decoracion de Follaje Seco",
        category: "Decoracion",
        description: "Decoracion con follaje seco.",
        price: "$3,850 MXN",
        priceValue: 3850,
        unit: "c/u",
        image: "/images/catalog/decor-dry-foliage.jpg",
      },
      {
        id: "vitroleros",
        name: "Vitroleros",
        category: "Decoracion",
        description: "Vitroleros decorativos para eventos.",
        price: "$330 MXN",
        priceValue: 330,
        unit: "c/u",
        image: "/images/catalog/decor-vitroleros.jpg",
      },
      {
        id: "serie-luces-vintage",
        name: "Serie de Luces Vintage (15m)",
        category: "Decoracion",
        description: "Serie de luces vintage de 15 metros cada una.",
        price: "$550 MXN",
        priceValue: 550,
        unit: "c/u",
        image: "/images/catalog/decor-string-lights.jpg",
      },
    ],
  },
  {
    id: "energia",
    name: "Plantas de Energia",
    description:
      "Plantas de luz profesionales para eventos en cualquier ubicacion.",
    icon: "zap",
    items: [
      {
        id: "planta-60kva",
        name: "Planta 60 KVA",
        category: "Plantas de Energia",
        description:
          "Planta de luz de 60 KVA. Incluye centro de carga. Costos dentro de la CD de Queretaro.",
        price: "$10,450 MXN",
        priceValue: 10450,
        unit: "8 hrs",
        image: "/images/catalog/power-60.jpg",
      },
      {
        id: "planta-40kva",
        name: "Planta 40 KVA",
        category: "Plantas de Energia",
        description:
          "Planta de luz de 40 KVA con traslado incluido.",
        price: "$7,700 MXN",
        priceValue: 7700,
        unit: "8 hrs",
        image: "/images/catalog/power-40.jpg",
      },
      {
        id: "planta-3000w",
        name: "Planta 3000W",
        category: "Plantas de Energia",
        description:
          "Planta compacta de 3000W con traslado incluido.",
        price: "$2,750 MXN",
        priceValue: 2750,
        unit: "8 hrs",
        image: "/images/catalog/power-3000.jpg",
      },
    ],
  },
  {
    id: "catering",
    name: "Catering & Alimentos",
    description:
      "Coffee break, snacks y servicio de alimentos para tus invitados.",
    icon: "utensils",
    items: [
      {
        id: "coffee-break",
        name: "Coffee Break",
        category: "Catering & Alimentos",
        description:
          "Servicio de coffee break con cafe, te, galletas y panes finos.",
        price: "$90 MXN",
        priceValue: 90,
        unit: "por persona",
        image: "/images/catalog/catering-coffee.jpg",
      },
      {
        id: "snacks",
        name: "Snacks / Mesa de Postres",
        category: "Catering & Alimentos",
        description:
          "Seleccion de snacks variados y bocadillos.",
        price: "$70 MXN",
        priceValue: 70,
        unit: "por persona",
        image: "/images/catalog/catering-snacks.jpg",
      },
    ],
  },
]

export function getAllItems(): CatalogItem[] {
  return catalog.flatMap((cat) => cat.items)
}

export function getCategory(id: string): CatalogCategory | undefined {
  return catalog.find((cat) => cat.id === id)
}
